### ISSUE TITLE
Psyco required

### ISSUE THREAD

**Issue by Lambdanaut** [phreeza/cells#1]
Psyco isn't really needed for the game. It helps a bunch I'm sure, but my computer runs fine without it. 

Replace

"
try:
  import psyco
  psyco.full()
finally:
  pass
"

with

"
try:
  import psyco
  psyco.full()

except (ImportError):
  pass
finally:
  pass
"

**Comment by swolchok** [comment]
Fixed in my fork, should be getting merged in tomorrow.

**Comment by phreeza** [comment]
Done, thanks.
