### ISSUE TITLE
Throws exception on first run

### ISSUE THREAD

**Issue by jgrigonis** [phreeza/cells#10]
You need these two lines at line 61 and 62:

```
    minds_str = str(config.get('minds', 'minds'))
    mind_list = [get_mind(n) for n in minds_str.split(',')]
```

Otherwise, you get an exception when the default.cfg is missing.  Here's the exception:

Traceback (most recent call last):
  File "cells.py", line 526, in <module>
    main()
  File "cells.py", line 70, in main
    print mind_list
NameError: global name 'mind_list' is not defined

**Comment by jgrigonis** [comment]
Sorry, this is the exception:

Traceback (most recent call last):
  File "cells.py", line 528, in <module>
    game = Game(bounds, mind_list, symmetric, -1)
NameError: global name 'mind_list' is not defined

**Comment by exupero** [comment]
Is this issue still open? I haven't had this trouble and I see the code mentioned above in the source.

**Comment by jgrigonis** [comment]
It needs to be in there twice (yuck).  Both in the try and except.  It only throws the exception when default.cfg doesn't exist yet.

**Comment by phreeza** [comment]
I ended up moving the mind_list generation out of the try..except. should work now
