### ISSUE TITLE
SyntaxError reading commandline arguments

### ISSUE THREAD

**Issue by CaseyBurns** [phreeza/cells#12]
I get this error, I suspect I don't have everything set up correctly.

`File "C:\Python31\cells\phreeza-cells-2b942c0\cells.py", line 49
    print 'Got error: %s' % e
                        ^
SyntaxError: invalid syntax`

**Comment by swolchok** [comment]
It looks like you're using Python 3.1. Python 3 is incompatible with Python 2, for which this game is written.

**Comment by CaseyBurns** [comment]
Installing Python 2.6.5 fix this issue. Thank you!
