### ISSUE TITLE
Have to use force quit on Ubuntu

### ISSUE THREAD

**Issue by exupero** [phreeza/cells#19]
I'm running it on Ubuntu 9.10 and anytime I run it I have to use force quit to kill it. It goes nicely, but it doesn't respond to the close button or Alt+F4.

**Comment by bartrail** [comment]
have the same issue in ubuntu 10.04 in 3 of 4 runs..

**Comment by phreeza** [comment]
Justin fixed this, will merge his changes in tonight.
