### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bartrail** [phreeza/cells#2]
I'm new to python and really interested in learning it with this nice game.. 
could you please provide any inline documentation to make it a bit easier to understand whats happening? :)

**Comment by phreeza** [comment]
Increasing this gradually, leaving some inline comments whenever I edit things.

**Comment by bartrail** [comment]
already noticed :) thanks
started a little modification of ben's mind yesterday... isn't that hard to learn ;)
But I think of an own little one too... is fun :D

**Comment by phreeza** [comment]
I think this hat gotten a bit better now, so i'm closing the issue
