### ISSUE TITLE
Possible memory leak??

### ISSUE THREAD

**Issue by kgraves** [phreeza/cells#23]
I'm not really sure, but the fps tanks once the game picks up.

**Comment by Lambdanaut** [comment]
I think it's more likely just because of the sheer amount of cells that are created so quickly. 

When you say "tank", what fps are you getting exactly?

**Comment by kgraves** [comment]
Woops, I meant to post this in my org's fork of the project, but I guess here is cool too.

Just to start off, I haven't researched or debugged this so I can't be sure if it's true, it was just consistently happening, and some of my friends also said that they had the same problem. So it only a few seconds after I start the game that it dramatically drops. The first FPS print out is 52.62 and within 5 seconds it tanks to 11.22. And within 15 seconds of the first print out, it was down to 5.28.

The above results are from a virtual box on my laptop, which may be some of the reason, but some other people I was working on it with, on various machines, were having some of the same issues.
