### ISSUE TITLE
I got an IndexError, but it's hard to reproduce

### ISSUE THREAD

**Issue by jgrigonis** [phreeza/cells#4]
Traceback (most recent call last):
  File "cells.py", line 471, in <module>
    game = Game()
  File "cells.py", line 113, in **init**
    self.agent_map.insert(self.agent_population)
  File "cells.py", line 301, in insert
    self.set(o.x, o.y, o)
  File "cells.py", line 245, in set
    self.values[x,y] = val
IndexError: index (300) out of range (0<=index<300) in dimension 1

**Comment by swolchok** [comment]
This probably happens when plants are generated at the edge of the map.

**Comment by phreeza** [comment]
I have added a tentative fix that places the plants 1 away from the edge. I'll close the issue for now.
